= Terraform known issues Cheat Sheet
Aurélie Vache <https://twitter.com/aurelievache>
:author: Aurélie Vache
:authorbio: Cloud Dev(Ops) at Continental
:pdf-width: 508mm
:pdf-height: 361mm
:version: v1.0.0

== Signature expired: xxxx is now earlier than xxx

If, suddently, you obtain an error message `Signature expired: xxx is now
earlier than xxx'`, like this:

Don’t worry it’s not an issue in the AWS account/user/credentials in terraform files

BUT it’s an issue in your local machine date and time!

So the solution is, simply: update your date and time to the good time ;-).

== AWS was not able to validate the provided access credentials

If, suddently, you obtain an error message _AWS was not able to validate the provided access credentials_, like this:

....
* data.aws_vpc.vpc-titi: data.aws_vpc.vpc-titi: 
AuthFailure: AWS was not able to validate the provided access credentials
status code: 401, request id: 9fbd5beb-e065-4933-ba67-2ceae9104c4c
....

No worries, it’s the same issue as above: your local/VM machine date and time is
not uptodate ;-).

== Error configuring the backend s3: RequestError: send request failed

Again, you changed nothing but suddently you obtain a strange error message:

....
Initializing the backend...
 
Error configuring the backend "s3": RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: Parent proxy unreacheable
...
....

It caused in reality by a proxy or a temporary issue between your network connectivity and AWS.